reviews:
  pre_merge_checks:
    custom_checks:

      - name: "Architecture Consistency"
        mode: "warning"
        instructions: "New files must follow the existing folder and project structure (e.g., services go in /Services). Request changes when a commit does not fit within the existing architecture."

      - name: "File & Class Name Consistency"
        mode: "warning"
        instructions: "A file name must match the primary class name inside it (e.g., MessagesService.cs → MessagesService). Request changes when the file name and class name do not correspond."

      - name: "Naming Conventions"
        mode: "error"
        instructions: "Follow standard C# naming: variables use camelCase, and classes, methods, and public members use PascalCase. Request changes when naming does not follow these conventions."

      - name: "Clean Code Principles"
        mode: "warning"
        instructions: "Functions should stay focused on a single responsibility and avoid unnecessary logic, loops, or logging. The tool should warn when a method becomes too long, too complex, or mixes multiple concerns."

      - name: "Unit Test Coverage"
        mode: "warning"
        instructions: "New logic should be supported by appropriate unit tests, especially for services and controllers. The tool should warn when a commit adds functionality without corresponding tests."

  path_instructions:
    - path: "**/*.cs"
      instructions: |
        Review all C# source code and ensure the following:

        - New files must follow the existing folder and project structure. Ensure commits align with the architectural layout.
        - File names must match the primary class name inside them. Flag mismatches between file and class names.
        - Variable names must be positive, clear, and non-confusing. Avoid negative or double-negative names.
        - Code must use a consistent indentation style across all methods and files. Flag inconsistent formatting.
        - Follow standard C# naming conventions: variables use camelCase, while classes, methods, and public members use PascalCase. Avoid inconsistent capitalization.
        - Functions should stay focused on a single responsibility. Avoid large or overly complex methods and unnecessary logic, loops, or logging.
        - New logic should be supported by appropriate unit tests, especially for services and controllers. Warn when functionality is added without corresponding tests.
