// Login for admin1
POST http://localhost:5097/api/v1/login/login HTTP/1.1
content-type: application/json

{
    "Username": "admin1" ,
    "Password": "password"
}

###

// Login for admin2
POST http://localhost:5097/api/v1/login/login HTTP/1.1
content-type: application/json

{
    "Username": "admin2" ,
    "Password": "tooeasytooguess"
}

###

// Login for a user
POST http://localhost:5097/api/v1/login/login HTTP/1.1
Content-Type: application/json

{
    "Username": "jordy@example.com",
    "Password": "secret"
}

###

// Login for a user
POST http://localhost:5097/api/v1/login/login HTTP/1.1
Content-Type: application/json

{
    "Username": "max@example.com",
    "Password": "secret"
}

###

// Login for a user
POST http://localhost:5097/api/v1/login/login HTTP/1.1
Content-Type: application/json

{
    "Username": "amer@example.com",
    "Password": "secret"
}

###

// Check if an admin is logged in
GET http://localhost:5097/api/v1/login/isadminloggedin HTTP/1.1

###

// Check if a regular user is logged in (via USER_SESSION_KEY)
GET http://localhost:5097/api/v1/login/isuserloggedin HTTP/1.1

###

// Logout
GET http://localhost:5097/api/v1/login/logout HTTP/1.1

###

// Create a user login
POST http://localhost:5097/api/v1/login/register HTTP/1.1
Content-Type: application/json

{
    "Username": "wowuser@example.com",
    "Password": "securepassword123",
    "FirstName": "Hank",
    "LastName": "Doe",
    "RecuringDays": "mo,tu,we"
}

###

// Login the new user
POST http://localhost:5097/api/v1/login/login HTTP/1.1
Content-Type: application/json

{
    "Username": "wowuser@example.com",
    "Password": "securepassword123"
}

###